import { Platform, StatusBar, StyleSheet } from "react-native";
import { COLORS } from "./theme";

export const appStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: COLORS.white,
  },
});

export const appNavigatorStyles = StyleSheet.create({
  loadingContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
  },
});

export const loginStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: COLORS.bgApp,
    justifyContent: "center",
    paddingHorizontal: 20,
  },
  header: {
    marginBottom: 28,
    alignItems: "center",
  },
  title: {
    fontSize: 28,
    fontWeight: "bold",
    color: COLORS.textPrimary,
    textAlign: "center",
  },
  subtitle: {
    marginTop: 8,
    fontSize: 15,
    color: COLORS.legacy6,
  },
  formCard: {
    backgroundColor: COLORS.white,
    borderRadius: 14,
    padding: 20,
    elevation: 4,
    shadowColor: COLORS.black,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 8,
  },
  inputContainer: {
    marginBottom: 16,
  },
  label: {
    fontSize: 14,
    fontWeight: "600",
    color: COLORS.legacy1,
    marginBottom: 8,
  },
  inputWrapper: {
    flexDirection: "row",
    alignItems: "center",
    borderWidth: 1,
    borderColor: COLORS.borderMuted,
    borderRadius: 10,
    backgroundColor: COLORS.oldInput,
    paddingHorizontal: 12,
  },
  input: {
    flex: 1,
    paddingVertical: 12,
    paddingHorizontal: 10,
    fontSize: 16,
    color: COLORS.textPrimary,
  },
  passwordToggle: {
    padding: 4,
  },
  button: {
    backgroundColor: COLORS.primary,
    borderRadius: 10,
    paddingVertical: 14,
    alignItems: "center",
    marginTop: 8,
  },
  buttonDisabled: {
    opacity: 0.75,
  },
  buttonText: {
    color: COLORS.white,
    fontSize: 16,
    fontWeight: "bold",
  },
});

export const dashboardStyles = StyleSheet.create({
  container: { flex: 1, backgroundColor: COLORS.bgSoft },
  loadingContainer: { flex: 1, justifyContent: "center", alignItems: "center" },
  header: {
    backgroundColor: COLORS.primaryDark,
    paddingTop: Platform.OS === "ios" ? 50 : 30,
    paddingBottom: 15,
    paddingHorizontal: 20,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  headerUserInfo: {
    flexDirection: "row",
    alignItems: "center",
  },
  profileIconContainer: {
    backgroundColor: COLORS.white,
    width: 46,
    height: 46,
    borderRadius: 23,
    justifyContent: "center",
    alignItems: "center",
    marginRight: 12,
    elevation: 3,
  },
  headerTitle: {
    fontSize: 20,
    fontWeight: "bold",
    color: COLORS.white,
  },
  headerSubtitle: {
    fontSize: 13,
    color: COLORS.surfaceAlt,
    marginTop: 2,
  },
  logoutButton: {
    padding: 8,
    backgroundColor: COLORS.overlayTint,
    borderRadius: 20,
  },
  quickActionsContainer: {
    flexDirection: "row",
    backgroundColor: COLORS.white,
    padding: 10,
    elevation: 2,
    gap: 10,
    justifyContent: "center",
  },
  quickActionBtn: {
    flex: 1,
    backgroundColor: COLORS.cardTint,
    padding: 10,
    borderRadius: 8,
    alignItems: "center",
  },
  quickActionText: {
    color: COLORS.primaryDark,
    fontWeight: "bold",
    fontSize: 12,
    marginTop: 4,
  },
});

export const addItemStyles = StyleSheet.create({
  container: { flex: 1, backgroundColor: COLORS.bgApp },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    padding: 16,
    paddingTop: 50,
    backgroundColor: COLORS.textPrimary,
    borderBottomWidth: 1,
    borderColor: COLORS.border,
  },
  headerTitle: { fontSize: 20, fontWeight: "bold", color: COLORS.white },
  content: { padding: 16, paddingBottom: 50 },
  imageContainer: {
    height: 120, // Smaller height
    borderRadius: 8,
    overflow: "hidden",
    marginBottom: 8,
    backgroundColor: COLORS.white,
    elevation: 2,
    borderWidth: 1,
    borderColor: COLORS.border,
  },
  image: { width: "100%", height: "100%" },
  imagePlaceholder: { flex: 1, justifyContent: "center", alignItems: "center" },
  imagePlaceholderText: { marginTop: 12, fontSize: 16, color: COLORS.textMuted },
  imageActionsRow: {
    marginBottom: 10,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  imageCountText: {
    fontSize: 13,
    color: COLORS.textSecondary,
    fontWeight: "600",
  },
  addMoreImageBtn: {
    backgroundColor: COLORS.primary,
    borderRadius: 8,
    paddingVertical: 8,
    paddingHorizontal: 10,
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  addMoreImageBtnText: {
    color: COLORS.white,
    fontSize: 12,
    fontWeight: "700",
  },
  imageThumbScroll: {
    marginBottom: 12,
  },
  imageThumbWrap: {
    width: 80,
    height: 80,
    borderRadius: 8,
    overflow: "hidden",
    marginRight: 10,
    position: "relative",
    backgroundColor: COLORS.surfaceAlt,
  },
  imageThumb: { width: "100%", height: "100%" },
  removeThumbBtn: {
    position: "absolute",
    top: 4,
    right: 4,
    width: 20,
    height: 20,
    borderRadius: 10,
    backgroundColor: COLORS.overlaySoft,
    alignItems: "center",
    justifyContent: "center",
  },
  inputContainer: { marginBottom: 16 },
  label: { fontSize: 16, fontWeight: "600", color: COLORS.textPrimary, marginBottom: 8 },
  input: {
    backgroundColor: COLORS.white,
    borderWidth: 1,
    borderColor: COLORS.border,
    borderRadius: 8,
    padding: 12,
    fontSize: 16,
  },
  chip: {
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: COLORS.primary,
    marginRight: 8,
    backgroundColor: COLORS.white,
    marginBottom: 5,
  },
  chipActive: { backgroundColor: COLORS.primary },
  chipText: { color: COLORS.primary, fontWeight: "600" },
  chipTextActive: { color: COLORS.white },
  dropdownTrigger: {
    backgroundColor: COLORS.white,
    borderWidth: 1,
    borderColor: COLORS.border,
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 12,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  dropdownText: {
    fontSize: 16,
    color: COLORS.textPrimary,
  },
  dropdownPlaceholder: {
    color: COLORS.textMuted,
  },
  dropdownMenu: {
    marginTop: 6,
    borderWidth: 1,
    borderColor: COLORS.border,
    borderRadius: 8,
    backgroundColor: COLORS.white,
    overflow: "hidden",
  },
  dropdownScroll: {
    maxHeight: 180,
  },
  dropdownItem: {
    paddingVertical: 12,
    paddingHorizontal: 12,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.divider,
  },
  dropdownItemText: {
    fontSize: 15,
    color: COLORS.textPrimary,
  },
  dropdownItemTextActive: {
    color: COLORS.primary,
    fontWeight: "700",
  },
  submitButton: {
    backgroundColor: COLORS.primary,
    borderRadius: 8,
    paddingVertical: 16,
    alignItems: "center",
    marginTop: 10,
    elevation: 4,
  },
  submitButtonText: { color: COLORS.white, fontSize: 18, fontWeight: "bold" },
});

export const editEntryStyles = StyleSheet.create({
  container: { flex: 1, backgroundColor: COLORS.bgApp },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    padding: 16,
    paddingTop: 50,
    backgroundColor: COLORS.textPrimary,
    borderBottomWidth: 1,
    borderColor: COLORS.border,
  },
  headerTitle: { fontSize: 20, fontWeight: "bold", color: COLORS.white },
  content: { padding: 16, paddingBottom: 50 },
  imageContainer: {
    height: 120, // Smaller height
    borderRadius: 8,
    overflow: "hidden",
    marginBottom: 8,
    backgroundColor: COLORS.white,
    elevation: 2,
    borderWidth: 1,
    borderColor: COLORS.border,
  },
  image: { width: "100%", height: "100%" },
  imageOverlay: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: COLORS.overlaySoft,
    padding: 12,
    alignItems: "center",
  },
  imageActionsRow: {
    marginBottom: 10,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  imageCountText: {
    fontSize: 13,
    color: COLORS.textSecondary,
    fontWeight: "600",
  },
  addMoreImageBtn: {
    backgroundColor: COLORS.primaryDark,
    borderRadius: 8,
    paddingVertical: 8,
    paddingHorizontal: 10,
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  addMoreImageBtnText: {
    color: COLORS.white,
    fontSize: 12,
    fontWeight: "700",
  },
  imageThumbScroll: {
    marginBottom: 12,
  },
  imageThumbWrap: {
    width: 80,
    height: 80,
    borderRadius: 8,
    overflow: "hidden",
    marginRight: 10,
    position: "relative",
    backgroundColor: COLORS.surfaceAlt,
  },
  imageThumb: { width: "100%", height: "100%" },
  removeThumbBtn: {
    position: "absolute",
    top: 4,
    right: 4,
    width: 20,
    height: 20,
    borderRadius: 10,
    backgroundColor: COLORS.overlaySoft,
    alignItems: "center",
    justifyContent: "center",
  },
  imagePlaceholder: { flex: 1, justifyContent: "center", alignItems: "center" },
  imagePlaceholderText: { marginTop: 12, fontSize: 16, color: COLORS.textMuted },
  inputContainer: { marginBottom: 16 },
  label: { fontSize: 16, fontWeight: "600", color: COLORS.textPrimary, marginBottom: 8 },
  input: {
    backgroundColor: COLORS.white,
    borderWidth: 1,
    borderColor: COLORS.border,
    borderRadius: 8,
    padding: 12,
    fontSize: 16,
  },
  chip: {
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: COLORS.primaryDark,
    marginRight: 8,
    backgroundColor: COLORS.white,
    marginBottom: 5,
  },
  chipActive: { backgroundColor: COLORS.primaryDark },
  chipText: { color: COLORS.primaryDark, fontWeight: "600" },
  chipTextActive: { color: COLORS.white },
  dropdownTrigger: {
    backgroundColor: COLORS.white,
    borderWidth: 1,
    borderColor: COLORS.border,
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 12,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  dropdownText: {
    fontSize: 16,
    color: COLORS.textPrimary,
  },
  dropdownPlaceholder: {
    color: COLORS.textMuted,
  },
  dropdownMenu: {
    marginTop: 6,
    borderWidth: 1,
    borderColor: COLORS.border,
    borderRadius: 8,
    backgroundColor: COLORS.white,
    overflow: "hidden",
  },
  dropdownScroll: {
    maxHeight: 180,
  },
  dropdownItem: {
    paddingVertical: 12,
    paddingHorizontal: 12,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.divider,
  },
  dropdownItemText: {
    fontSize: 15,
    color: COLORS.textPrimary,
  },
  dropdownItemTextActive: {
    color: COLORS.primaryDark,
    fontWeight: "700",
  },
  submitButton: {
    backgroundColor: COLORS.primaryDark,
    borderRadius: 8,
    paddingVertical: 16,
    alignItems: "center",
    marginTop: 10,
    elevation: 4,
  },
  submitButtonText: { color: COLORS.white, fontSize: 18, fontWeight: "bold" },
});

export const viewEntryStyles = StyleSheet.create({
  container: { flex: 1, backgroundColor: COLORS.bgApp },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    padding: 16,
    paddingTop: 50,
    backgroundColor: COLORS.textPrimary,
    borderBottomWidth: 1,
    borderColor: COLORS.border,
  },
  headerTitle: { fontSize: 20, fontWeight: "bold", color: COLORS.white },
  content: { padding: 16 },
  imageContainer: {
    width: "100%",
    height: 250,
    borderRadius: 12,
    overflow: "hidden",
    marginBottom: 20,
    backgroundColor: COLORS.white,
    elevation: 3,
  },
  image: { width: "100%", height: "100%" },
  imagePlaceholder: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: COLORS.bgApp,
  },
  card: {
    backgroundColor: COLORS.white,
    padding: 20,
    borderRadius: 12,
    elevation: 2,
  },
  title: { fontSize: 24, fontWeight: "bold", color: COLORS.textPrimary, marginBottom: 4 },
  price: {
    fontSize: 22,
    fontWeight: "bold",
    color: COLORS.primary,
    marginBottom: 20,
  },
  row: {
    flexDirection: "row",
    justifyContent: "space-between",
    paddingVertical: 8,
    borderBottomWidth: 1,
    borderColor: COLORS.surfaceAlt,
  },
  label: { fontSize: 16, color: COLORS.textSecondary, fontWeight: "600" },
  value: { fontSize: 16, color: COLORS.textPrimary },
  remarksText: {
    fontSize: 15,
    color: COLORS.legacy2,
    marginTop: 4,
    fontStyle: "italic",
    backgroundColor: COLORS.bgApp,
    padding: 10,
    borderRadius: 8,
  },
  viewerContainer: {
    flex: 1,
    backgroundColor: COLORS.overlayStrong,
    justifyContent: "center",
    alignItems: "center",
  },
  viewerClose: { position: "absolute", top: 50, right: 20, zIndex: 10 },
  viewerImage: { width: "100%", height: "80%" },
});

export const userManagementStyles = StyleSheet.create({
  container: { flex: 1, backgroundColor: COLORS.bgApp },
  header: {
    backgroundColor: COLORS.textPrimary,
    paddingTop: 50,
    paddingBottom: 15,
    paddingHorizontal: 20,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  headerTitle: { fontSize: 20, fontWeight: "bold", color: COLORS.white },
  formCard: {
    backgroundColor: COLORS.white,
    padding: 16,
    borderRadius: 12,
    marginBottom: 20,
    elevation: 2,
  },
  formTitle: { fontSize: 18, fontWeight: "bold", color: COLORS.textPrimary },
  label: {
    fontSize: 14,
    fontWeight: "600",
    color: COLORS.textSecondary,
    marginBottom: 6,
    marginTop: 8,
  },
  input: {
    borderWidth: 1,
    borderColor: COLORS.border,
    borderRadius: 8,
    padding: 12,
    marginBottom: 4,
    backgroundColor: COLORS.bgApp,
  },
  roleRow: { flexDirection: "row", gap: 10, marginVertical: 8 },
  roleChip: {
    flex: 1,
    padding: 8,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: COLORS.primaryDark,
    alignItems: "center",
  },
  roleChipActive: { backgroundColor: COLORS.primaryDark },
  roleTextDefault: { color: COLORS.primaryDark, fontWeight: "600", fontSize: 12 },
  roleTextActive: { color: COLORS.white },
  submitBtn: {
    backgroundColor: COLORS.primary,
    padding: 14,
    borderRadius: 8,
    alignItems: "center",
    marginTop: 10,
  },
  submitBtnText: { color: COLORS.white, fontWeight: "bold", fontSize: 16 },
  userCard: {
    backgroundColor: COLORS.white,
    padding: 16,
    borderRadius: 12,
    marginBottom: 10,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    elevation: 1,
  },
  userName: { fontSize: 16, fontWeight: "bold", color: COLORS.textPrimary },
  userDetails: { fontSize: 13, color: COLORS.textSecondary, marginTop: 4 },
  userBranch: {
    fontSize: 12,
    color: COLORS.legacy8,
    marginTop: 4,
    fontWeight: "600",
  },
  roleBadge: {
    backgroundColor: COLORS.cardTint,
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 12,
  },
  roleText: { color: COLORS.primaryDark, fontSize: 12, fontWeight: "bold" },
  editBtnSmall: {
    backgroundColor: COLORS.primaryDark,
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 8,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: COLORS.overlay,
    justifyContent: "center",
    padding: 20,
  },
  modalContent: { backgroundColor: COLORS.white, borderRadius: 16, padding: 20 },
});

export const itemManagementStyles = StyleSheet.create({
  container: { flex: 1, backgroundColor: COLORS.bgApp },
  header: {
    backgroundColor: COLORS.textPrimary,
    paddingTop: 50,
    paddingBottom: 15,
    paddingHorizontal: 20,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  headerTitle: { fontSize: 20, fontWeight: "bold", color: COLORS.white },
  formContainer: {
    backgroundColor: COLORS.white,
    padding: 16,
    borderBottomWidth: 1,
    borderColor: COLORS.border,
  },
  branchSubtitle: {
    fontSize: 14,
    color: COLORS.textSecondary,
    marginBottom: 10,
    fontWeight: "bold",
  },
  inputRow: { flexDirection: "row", gap: 10 },
  input: {
    flex: 1,
    borderWidth: 1,
    borderColor: COLORS.border,
    borderRadius: 8,
    padding: 12,
    backgroundColor: COLORS.bgApp,
  },
  addBtn: {
    backgroundColor: COLORS.primary,
    width: 50,
    borderRadius: 8,
    justifyContent: "center",
    alignItems: "center",
  },
  itemCard: {
    backgroundColor: COLORS.white,
    padding: 16,
    borderRadius: 8,
    marginBottom: 10,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    elevation: 1,
  },
  itemName: { fontSize: 16, fontWeight: "bold", color: COLORS.textPrimary },
  itemDate: { fontSize: 12, color: COLORS.textMuted },
  emptyText: { textAlign: "center", color: COLORS.textMuted, marginTop: 20 },
});

export const vendorLedgerStyles = StyleSheet.create({
  container: { flex: 1, backgroundColor: COLORS.bgApp },
  header: {
    backgroundColor: COLORS.textPrimary,
    paddingTop: 50,
    paddingBottom: 15,
    paddingHorizontal: 20,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  headerTitle: { fontSize: 20, fontWeight: "bold", color: COLORS.white },
  balanceHeaderCard: {
    backgroundColor: COLORS.white,
    margin: 16,
    padding: 20,
    borderRadius: 12,
    alignItems: "center",
    elevation: 3,
  },
  balanceHeaderLabel: {
    fontSize: 14,
    color: COLORS.textSecondary,
    fontWeight: "600",
    textTransform: "uppercase",
  },
  balanceHeaderAmount: { fontSize: 32, fontWeight: "bold", marginTop: 4 },
  ledgerCard: {
    backgroundColor: COLORS.white,
    padding: 16,
    borderRadius: 12,
    marginBottom: 10,
    flexDirection: "row",
    alignItems: "center",
    elevation: 1,
  },
  ledgerIconContainer: { marginRight: 12, width: 40, alignItems: "center" },
  ledgerTitle: { fontSize: 15, fontWeight: "bold", color: COLORS.textPrimary },
  ledgerDate: { fontSize: 12, color: COLORS.textMuted, marginTop: 2 },
  ledgerRemarks: {
    fontSize: 12,
    color: COLORS.textSecondary,
    fontStyle: "italic",
    marginTop: 4,
  },
  ledgerVendorComment: {
    fontSize: 12,
    color: COLORS.textPrimary,
    marginTop: 4,
    fontWeight: "600",
  },
  ledgerRightColumn: {
    marginLeft: 8,
    alignItems: "flex-end",
    justifyContent: "space-between",
    minHeight: 54,
  },
  commentBtn: {
    width: 28,
    height: 28,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: COLORS.dividerStrong,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: COLORS.surfaceAlt,
  },
  ledgerAmount: { fontSize: 16, fontWeight: "bold" },
  actionRow: {
    position: "absolute",
    bottom: 20,
    left: 20,
    right: 20,
    flexDirection: "row",
    gap: 10,
  },
  fab: {
    backgroundColor: COLORS.primary,
    padding: 16,
    borderRadius: 12,
    justifyContent: "center",
    alignItems: "center",
    elevation: 6,
  },
  recordPaymentFab: { flex: 3, flexDirection: "row" },
  addDueFab: { flex: 1, backgroundColor: COLORS.primaryDark },
  addDueFabText: {
    color: COLORS.white,
    fontWeight: "700",
    fontSize: 11,
    marginTop: 2,
  },
  proofBtn: {
    flexDirection: "row",
    alignItems: "center",
    marginTop: 6,
    backgroundColor: COLORS.cardTint,
    alignSelf: "flex-start",
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 6,
  },
  proofText: {
    fontSize: 11,
    color: COLORS.accentSoft,
    fontWeight: "bold",
    marginLeft: 4,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: COLORS.overlay,
    justifyContent: "flex-end",
  },
  modalContent: {
    backgroundColor: COLORS.white,
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    padding: 24,
    paddingBottom: 40,
  },
  modalTitle: { fontSize: 18, fontWeight: "bold", color: COLORS.textPrimary },
  label: {
    fontSize: 14,
    fontWeight: "600",
    color: COLORS.textSecondary,
    marginBottom: 8,
    marginTop: 12,
  },
  input: {
    borderWidth: 1,
    borderColor: COLORS.border,
    borderRadius: 8,
    padding: 12,
    fontSize: 16,
    backgroundColor: COLORS.bgApp,
  },
  submitBtn: {
    backgroundColor: COLORS.primary,
    padding: 16,
    borderRadius: 8,
    alignItems: "center",
    marginTop: 24,
  },
  submitBtnText: { color: COLORS.white, fontWeight: "bold", fontSize: 16 },
  uploadBtn: {
    backgroundColor: COLORS.bgApp,
    borderWidth: 1,
    borderColor: COLORS.border,
    borderStyle: "dashed",
    borderRadius: 8,
    height: 80,
    justifyContent: "center",
    alignItems: "center",
    flexDirection: "row",
  },
  uploadBtnText: { color: COLORS.primary, fontWeight: "600", marginLeft: 8 },
  imagePreviewContainer: {
    height: 120,
    width: "100%",
    borderRadius: 8,
    overflow: "hidden",
    position: "relative",
  },
  imagePreview: { width: "100%", height: "100%", backgroundColor: COLORS.surfaceAlt },
  removeImageBtn: {
    position: "absolute",
    top: 8,
    right: 8,
    backgroundColor: COLORS.overlaySoft,
    padding: 6,
    borderRadius: 20,
  },
  viewerContainer: {
    flex: 1,
    backgroundColor: COLORS.overlayStrong,
    justifyContent: "center",
    alignItems: "center",
  },
  viewerClose: { position: "absolute", top: 50, right: 20, zIndex: 10 },
  viewerImage: { width: "100%", height: "80%" },
  commentModalBackdrop: {
    flex: 1,
    backgroundColor: COLORS.overlaySoft,
    justifyContent: "center",
    padding: 20,
  },
  commentModalCard: {
    backgroundColor: COLORS.white,
    borderRadius: 12,
    padding: 16,
    elevation: 3,
  },
  commentModalTitle: {
    fontSize: 16,
    fontWeight: "700",
    color: COLORS.textPrimary,
    marginBottom: 10,
  },
  commentInput: {
    borderWidth: 1,
    borderColor: COLORS.dividerStrong,
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 8,
    minHeight: 84,
    textAlignVertical: "top",
    color: COLORS.textPrimary,
    backgroundColor: COLORS.white,
  },
  commentActions: {
    marginTop: 12,
    flexDirection: "row",
    justifyContent: "flex-end",
  },
  commentCancelBtn: {
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 8,
    backgroundColor: COLORS.surfaceAlt,
  },
  commentCancelText: {
    fontSize: 13,
    fontWeight: "600",
    color: COLORS.textSecondary,
  },
  commentSaveBtn: {
    marginLeft: 10,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 8,
    backgroundColor: COLORS.accentSoft,
  },
  commentSaveText: {
    fontSize: 13,
    fontWeight: "700",
    color: COLORS.white,
  },
});

export const itemsCalendarStyles = StyleSheet.create({
  container: { flex: 1, backgroundColor: COLORS.oldNeutral },
  headerRow: {
    padding: 16,
    backgroundColor: COLORS.white,
    borderBottomWidth: 1,
    borderColor: COLORS.surfaceAlt,
    flexDirection: "row",
    justifyContent: "space-between",
  },
  dateTitle: { fontSize: 16, fontWeight: "bold", color: COLORS.legacy3 },
  empty: { textAlign: "center", marginTop: 20, color: COLORS.legacy7 },
  fab: {
    position: "absolute",
    right: 20,
    bottom: 20,
    backgroundColor: COLORS.primaryDark,
    width: 56,
    height: 56,
    borderRadius: 28,
    justifyContent: "center",
    alignItems: "center",
    elevation: 6,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: COLORS.overlay,
    justifyContent: "center",
    padding: 20,
  },
  modalContent: { backgroundColor: COLORS.white, borderRadius: 12, padding: 20 },
  modalTitle: { fontSize: 18, fontWeight: "bold", marginBottom: 15 },
  input: {
    borderWidth: 1,
    borderColor: COLORS.border,
    borderRadius: 8,
    padding: 10,
    height: 80,
    textAlignVertical: "top",
    marginBottom: 15,
  },
  modalBtns: { flexDirection: "row", justifyContent: "flex-end", gap: 10 },
  btnCancel: { padding: 10 },
  btnSave: {
    backgroundColor: COLORS.primaryDark,
    padding: 10,
    borderRadius: 8,
    minWidth: 80,
    alignItems: "center",
  },
  btnTextCancel: { color: COLORS.textSecondary },
  btnTextSave: { color: COLORS.white, fontWeight: "bold" },
});

export const analyticsTabStyles = StyleSheet.create({
  container: { flex: 1, backgroundColor: COLORS.bgSoft, padding: 16 },
  centered: { flex: 1, justifyContent: "center", alignItems: "center" },
  titleRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 16,
  },
  pageTitle: {
    fontSize: 28,
    fontWeight: "800",
    color: COLORS.textPrimary,
    letterSpacing: 0.2,
  },
  pageSubtitle: {
    marginTop: 2,
    fontSize: 13,
    color: COLORS.legacy4,
    fontWeight: "500",
  },
  badgePill: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 999,
    gap: 4,
  },
  badgeText: { fontSize: 12, fontWeight: "700" },
  emptyText: {
    textAlign: "center",
    color: COLORS.legacy10,
    marginTop: 40,
    fontSize: 16,
  },
  selectorContainer: {
    marginBottom: 16,
    backgroundColor: COLORS.white,
    borderRadius: 14,
    padding: 14,
    borderWidth: 1,
    borderColor: COLORS.surfaceAlt,
  },
  sectionLabel: {
    fontSize: 14,
    fontWeight: "700",
    color: COLORS.legacy1,
    marginBottom: 12,
  },
  analyticsPresetRow: {
    flexDirection: "row",
    gap: 8,
    marginBottom: 12,
  },
  analyticsPresetChip: {
    flex: 1,
    backgroundColor: COLORS.cardTint,
    borderRadius: 8,
    paddingVertical: 9,
    alignItems: "center",
    borderWidth: 1,
    borderColor: COLORS.borderSoft,
  },
  analyticsPresetChipActive: {
    backgroundColor: COLORS.primaryDark,
    borderColor: COLORS.primaryDark,
  },
  analyticsPresetText: {
    color: COLORS.primaryDark,
    fontSize: 12,
    fontWeight: "700",
  },
  analyticsPresetTextActive: {
    color: COLORS.white,
  },
  analyticsDateRow: {
    flexDirection: "row",
    gap: 10,
  },
  chipScroll: { flexDirection: "row" },
  chip: {
    paddingHorizontal: 14,
    paddingVertical: 9,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: COLORS.primaryDark,
    marginRight: 8,
    backgroundColor: COLORS.bgSoft,
  },
  chipActive: { backgroundColor: COLORS.primaryDark, borderColor: COLORS.primaryDark },
  chipText: { color: COLORS.primaryDark, fontWeight: "700", fontSize: 13 },
  chipTextActive: { color: COLORS.white },
  chartCard: {
    backgroundColor: COLORS.white,
    padding: 14,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: COLORS.surfaceAlt,
    elevation: 2,
    marginBottom: 18,
    alignItems: "center",
  },
  chartTitle: { fontSize: 20, fontWeight: "800", color: COLORS.textStrong },
  chartSubtitle: {
    marginTop: 3,
    fontSize: 13,
    color: COLORS.legacy9,
    fontWeight: "500",
    marginBottom: 10,
  },
  chartTypeRow: {
    flexDirection: "row",
    gap: 8,
    marginBottom: 10,
  },
  chartTypeChip: {
    paddingVertical: 7,
    paddingHorizontal: 12,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: COLORS.borderSoft,
    backgroundColor: COLORS.bgSoft,
  },
  chartTypeChipActive: {
    backgroundColor: COLORS.primaryDark,
    borderColor: COLORS.primaryDark,
  },
  chartTypeText: {
    fontSize: 12,
    color: COLORS.primaryDark,
    fontWeight: "700",
  },
  chartTypeTextActive: {
    color: COLORS.white,
  },
  chartStyle: { borderRadius: 16 },
  selectedPointCard: {
    marginTop: 10,
    backgroundColor: COLORS.cardTint,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: COLORS.borderSoft,
    paddingVertical: 8,
    paddingHorizontal: 10,
    alignSelf: "stretch",
  },
  selectedPointTitle: {
    fontSize: 12,
    fontWeight: "700",
    color: COLORS.textPrimary,
  },
  selectedPointBody: {
    marginTop: 2,
    fontSize: 12,
    color: COLORS.textSecondary,
    fontWeight: "600",
  },
  chartHintText: {
    marginTop: 8,
    fontSize: 12,
    color: COLORS.textSecondary,
    fontStyle: "italic",
  },
  analyticsLegendWrap: {
    marginTop: 12,
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "center",
    gap: 12,
  },
  analyticsLegendItem: {
    flexDirection: "row",
    alignItems: "center",
  },
  analyticsLegendDot: {
    width: 10,
    height: 10,
    borderRadius: 5,
    marginRight: 6,
  },
  analyticsLegendText: {
    fontSize: 12,
    color: COLORS.textSecondary,
    fontWeight: "600",
  },
  statsRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    gap: 12,
    marginBottom: 12,
  },
  statCard: {
    flex: 1,
    backgroundColor: COLORS.white,
    paddingVertical: 18,
    paddingHorizontal: 14,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: COLORS.surfaceAlt,
    elevation: 1,
    alignItems: "center",
  },
  statLabel: {
    fontSize: 13,
    color: COLORS.legacy4,
    marginBottom: 8,
    fontWeight: "700",
  },
  statValueSpent: { fontSize: 21, fontWeight: "800", color: COLORS.danger },
  statValueQty: { fontSize: 21, fontWeight: "800", color: COLORS.primary },
  modalOverlay: {
    flex: 1,
    backgroundColor: COLORS.overlay,
    justifyContent: "flex-end",
  },
  modalContent: {
    backgroundColor: COLORS.white,
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    padding: 24,
    paddingBottom: 40,
  },
  modalTitle: { fontSize: 18, fontWeight: "bold", color: COLORS.textPrimary },
  label: { fontSize: 12, fontWeight: "600", color: COLORS.legacy5, marginBottom: 8 },
  presetChip: {
    flex: 1,
    backgroundColor: COLORS.cardTint,
    paddingVertical: 10,
    borderRadius: 8,
    alignItems: "center",
  },
  presetText: { color: COLORS.accent, fontWeight: "bold", fontSize: 13 },
  dateSelector: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: COLORS.bgApp,
    borderWidth: 1,
    borderColor: COLORS.border,
    borderRadius: 8,
    padding: 12,
    gap: 8,
  },
  dateText: { fontSize: 15, color: COLORS.textPrimary, fontWeight: "500" },
  submitBtn: {
    backgroundColor: COLORS.accent,
    padding: 16,
    borderRadius: 8,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
  },
  submitBtnText: { color: COLORS.white, fontWeight: "bold", fontSize: 16 },
});

export const paymentsTabStyles = StyleSheet.create({
  container: { flex: 1, backgroundColor: COLORS.bgMuted },
  centered: { flex: 1, justifyContent: "center", alignItems: "center" },
  pageTitle: {
    fontSize: 18,
    fontWeight: "bold",
    color: COLORS.textPrimary,
    marginBottom: 16,
  },
  emptyText: { textAlign: "center", color: COLORS.textSubtle, marginTop: 20 },
  adminBranchContainer: {
    backgroundColor: COLORS.white,
    borderRadius: 12,
    marginBottom: 12,
    elevation: 2,
    overflow: "hidden",
  },
  adminBranchHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    padding: 16,
    backgroundColor: COLORS.cardTint,
  },
  adminBranchName: { fontSize: 18, fontWeight: "bold", color: COLORS.textPrimary },
  adminBranchSub: { fontSize: 13, color: COLORS.legacy5, marginTop: 4 },
  adminExpandedContent: { padding: 12, backgroundColor: COLORS.panelBg },
  vendorCard: {
    backgroundColor: COLORS.white,
    padding: 16,
    borderRadius: 12,
    marginBottom: 12,
    flexDirection: "row",
    alignItems: "center",
    elevation: 1,
    borderWidth: 1,
    borderColor: COLORS.dividerSoft,
  },
  vendorIcon: {
    backgroundColor: COLORS.cardTint,
    padding: 12,
    borderRadius: 25,
    marginRight: 12,
  },
  vendorInfo: { flex: 1 },
  vendorName: { fontSize: 16, fontWeight: "bold", color: COLORS.textPrimary },
  vendorDetail: { fontSize: 12, color: COLORS.textSubtle, marginTop: 2 },
  balanceContainer: { alignItems: "flex-end" },
  balanceLabel: {
    fontSize: 10,
    color: COLORS.legacy5,
    textTransform: "uppercase",
    fontWeight: "bold",
  },
  balanceAmount: { fontSize: 18, fontWeight: "bold", marginTop: 2 },
  vendorHeaderCard: {
    backgroundColor: COLORS.white,
    margin: 16,
    padding: 24,
    borderRadius: 12,
    alignItems: "center",
    elevation: 3,
  },
  vendorHeaderLabel: {
    fontSize: 14,
    color: COLORS.legacy5,
    fontWeight: "600",
    textTransform: "uppercase",
  },
  vendorHeaderAmount: { fontSize: 36, fontWeight: "bold", marginTop: 8 },
  branchBalanceCard: {
    backgroundColor: COLORS.white,
    marginHorizontal: 16,
    marginBottom: 12,
    padding: 14,
    borderRadius: 12,
    elevation: 1,
  },
  branchBalanceTitle: {
    fontSize: 13,
    color: COLORS.textSecondary,
    fontWeight: "700",
    marginBottom: 8,
    textTransform: "uppercase",
  },
  branchBalanceRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingVertical: 6,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.dividerSoft,
  },
  branchBalanceName: { fontSize: 14, color: COLORS.textPrimary, fontWeight: "600" },
  branchBalanceAmount: { fontSize: 14, fontWeight: "700" },
  ledgerCard: {
    backgroundColor: COLORS.white,
    padding: 16,
    borderRadius: 12,
    marginBottom: 10,
    flexDirection: "row",
    alignItems: "center",
    elevation: 1,
  },
  ledgerIconContainer: { marginRight: 12, width: 40, alignItems: "center" },
  ledgerTitle: { fontSize: 15, fontWeight: "bold", color: COLORS.textPrimary },
  ledgerDate: { fontSize: 12, color: COLORS.textSubtle, marginTop: 2 },
  ledgerBranch: {
    fontSize: 12,
    color: COLORS.textSecondary,
    marginTop: 4,
    fontWeight: "600",
  },
  ledgerRemarks: {
    fontSize: 12,
    color: COLORS.legacy5,
    fontStyle: "italic",
    marginTop: 4,
  },
  ledgerVendorComment: {
    fontSize: 12,
    color: COLORS.textPrimary,
    marginTop: 4,
    fontWeight: "600",
  },
  proofBtn: {
    flexDirection: "row",
    alignItems: "center",
    marginTop: 8,
    backgroundColor: COLORS.cardTint,
    alignSelf: "flex-start",
    paddingHorizontal: 8,
    paddingVertical: 6,
    borderRadius: 8,
  },
  proofThumb: {
    width: 28,
    height: 28,
    borderRadius: 4,
    marginRight: 8,
    backgroundColor: COLORS.surfaceAlt,
  },
  proofText: {
    fontSize: 11,
    color: COLORS.accentSoft,
    fontWeight: "bold",
  },
  ledgerAmount: { fontSize: 16, fontWeight: "bold" },
  ledgerRightColumn: {
    marginLeft: 8,
    alignItems: "flex-end",
    justifyContent: "space-between",
    minHeight: 54,
  },
  commentBtn: {
    width: 28,
    height: 28,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: COLORS.dividerStrong,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: COLORS.surfaceAlt,
  },
  commentModalBackdrop: {
    flex: 1,
    backgroundColor: COLORS.overlaySoft,
    justifyContent: "center",
    padding: 20,
  },
  commentModalCard: {
    backgroundColor: COLORS.white,
    borderRadius: 12,
    padding: 16,
    elevation: 3,
  },
  commentModalTitle: {
    fontSize: 16,
    fontWeight: "700",
    color: COLORS.textPrimary,
    marginBottom: 10,
  },
  commentInput: {
    borderWidth: 1,
    borderColor: COLORS.dividerStrong,
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 8,
    minHeight: 84,
    textAlignVertical: "top",
    color: COLORS.textPrimary,
    backgroundColor: COLORS.white,
  },
  commentActions: {
    marginTop: 12,
    flexDirection: "row",
    justifyContent: "flex-end",
  },
  commentCancelBtn: {
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 8,
    backgroundColor: COLORS.surfaceAlt,
  },
  commentCancelText: {
    fontSize: 13,
    fontWeight: "600",
    color: COLORS.textSecondary,
  },
  commentSaveBtn: {
    marginLeft: 10,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 8,
    backgroundColor: COLORS.accentSoft,
  },
  commentSaveText: {
    fontSize: 13,
    fontWeight: "700",
    color: COLORS.white,
  },
  viewerContainer: {
    flex: 1,
    backgroundColor: COLORS.overlayStrong,
    justifyContent: "center",
    alignItems: "center",
  },
  viewerClose: { position: "absolute", top: 50, right: 20, zIndex: 10 },
  viewerImage: { width: "100%", height: "80%" },
});

export const setupProfileModalStyles = StyleSheet.create({
  overlay: {
    flex: 1,
    backgroundColor: COLORS.overlaySoft,
    justifyContent: "center",
    padding: 20,
  },
  card: {
    backgroundColor: COLORS.white,
    borderRadius: 16,
    padding: 24,
    elevation: 5,
    shadowColor: COLORS.black,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    position: "relative",
  },
  closeBtn: {
    position: "absolute",
    top: 16,
    right: 16,
    zIndex: 10,
    padding: 4,
  },
  title: {
    fontSize: 24,
    fontWeight: "bold",
    color: COLORS.textPrimary,
    textAlign: "center",
    marginBottom: 8,
    marginTop: 8,
  },
  subtitle: {
    fontSize: 14,
    color: COLORS.textSecondary,
    textAlign: "center",
    marginBottom: 24,
    lineHeight: 20,
  },
  inputContainer: {
    marginBottom: 16,
  },
  label: {
    fontSize: 14,
    fontWeight: "600",
    color: COLORS.textPrimary,
    marginBottom: 8,
  },
  input: {
    borderWidth: 1,
    borderColor: COLORS.border,
    borderRadius: 8,
    padding: 12,
    fontSize: 16,
    backgroundColor: COLORS.bgApp,
  },
  button: {
    backgroundColor: COLORS.primary,
    paddingVertical: 14,
    borderRadius: 8,
    alignItems: "center",
    marginTop: 10,
  },
  buttonText: {
    color: COLORS.white,
    fontSize: 16,
    fontWeight: "bold",
  },
});

export const entryCardStyles = StyleSheet.create({
  card: {
    backgroundColor: COLORS.white,
    marginHorizontal: 16,
    marginBottom: 12,
    borderRadius: 12,
    flexDirection: "row",
    height: 115,
    overflow: "hidden",
    elevation: 2,
    shadowColor: COLORS.black,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 3,
  },
  image: { width: 95, height: "100%", backgroundColor: COLORS.surfaceAlt },
  content: { flex: 1, padding: 10, justifyContent: "space-between" },
  header: { flexDirection: "row", justifyContent: "space-between" },
  title: {
    fontSize: 15,
    fontWeight: "bold",
    color: COLORS.textPrimary,
    flex: 1,
    marginRight: 8,
  },
  price: { fontSize: 15, fontWeight: "bold", color: COLORS.primary },
  detail: { fontSize: 13, color: COLORS.textSecondary },
  metaRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginTop: 4,
  },
  date: { fontSize: 11, color: COLORS.textMuted },
  badge: { paddingHorizontal: 8, paddingVertical: 2, borderRadius: 4 },
  badgePending: { backgroundColor: COLORS.warningBg },
  badgeVerified: { backgroundColor: COLORS.successBg },
  badgeText: { fontSize: 10, fontWeight: "bold" },
  textPending: { color: COLORS.warningText },
  textVerified: { color: COLORS.successText },
  subText: { fontSize: 11, color: COLORS.oldText, marginTop: 4 },
  commentText: {
    fontSize: 10,
    color: COLORS.info,
    marginTop: 2,
    fontStyle: "italic",
  },
  actions: {
    width: 40,
    justifyContent: "center",
    alignItems: "center",
    borderLeftWidth: 1,
    borderLeftColor: COLORS.divider,
  },
  actionBtn: { padding: 8 },
});

export const analyticsChartStyles = StyleSheet.create({
  container: {
    backgroundColor: COLORS.white,
    borderRadius: 16,
    padding: 16,
    marginBottom: 16,
    elevation: 2,
    margin: 16,
  },
  title: { fontSize: 18, fontWeight: "bold", color: COLORS.textPrimary, marginBottom: 16 },
  chart: { marginVertical: 8, borderRadius: 16 },
  statsRow: { flexDirection: "row", gap: 12, marginTop: 16 },
  statCard: {
    flex: 1,
    backgroundColor: COLORS.bgApp,
    padding: 12,
    borderRadius: 12,
    alignItems: "center",
  },
  statLabel: { fontSize: 12, color: COLORS.textSecondary, marginBottom: 4 },
  statValue: { fontSize: 20, fontWeight: "bold", color: COLORS.primary },
});
